export const subScoresFromSetup = (setup) => ({
  adr: setup.score_adr,
  ascending_support: setup.score_ascending_support,
  base_age: setup.score_base_age,
  box_tightness: setup.score_box_tightness,
  breadth_bonus: setup.score_breadth_bonus,
  contraction: setup.score_contraction,
  high_proximity: setup.score_high_proximity,
  lps_tightness: setup.score_lps_tightness,
  oscillation: setup.score_oscillation,
  rs_bonus: setup.score_rs_bonus,
  touch_density: setup.score_touch_density,
  uptrend_bonus: setup.score_uptrend_bonus,
  vol_contraction: setup.score_vol_contraction,
  atr_squeeze: setup.score_atr_squeeze,
});
